### ISSUE TITLE
Version update of FeedLoader

### ISSUE THREAD

**Issue by BaseTakumiYamada** [google/feedloader#1]
@google-admin @google-ospo-team 
Hello.
Forgive me if I did not know the appropriate mentions

I have a question about feedloader.
If the version of ContentAPI is upgraded in the future, will the version of feedloader be updated to follow?

**Comment by BaseTakumiYamada** [comment]
@vmichon @rihito0907 @starmandeluxe 
I don't know the address for Mentions, so I'll add the committer's people as well.

**Comment by rihito0907** [comment]
@BaseTakumiYamada 
We will consider upgrading if the current version of Content API is deprecated.

**Comment by BaseTakumiYamada** [comment]
So you will continue to support us.
Thank you for clearing up my questions.
